### ISSUE TITLE
JavaScript heap out of memory error

### ISSUE THREAD

**Issue by Chris-Boyle** [SelectQuoteLabs/ancillary-external-app#7]
While working in an app created from this project I have ran into the JS out of memory error twice.  I am not doing anything crazy to my knowledge so I am thinking it is more of a project issue.

```
nextjs  | wait  - compiling...
nextjs  | 
nextjs  | <--- Last few GCs --->
nextjs  | 
nextjs  | [19:0x55e55164cc60] 27563500 ms: Mark-sweep (reduce) 995.2 (1002.8) -> 995.1 (1004.5) MB, 1551.9 / 1.7 ms  (+ 280.6 ms in 31 steps since start of marking, biggest step 27.3 ms, walltime since start of marking 1910 ms) (average mu = 0.072, current mu = 0.0
nextjs  | 
nextjs  | <--- JS stacktrace --->
nextjs  | 
nextjs  | FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
nextjs exited with code 0
```

**Comment by SeanGroff** [comment]
@Chris-Boyle What version of `next-auth` are you running in the package.json?

**Comment by Chris-Boyle** [comment]
Currently running "3.15.5" @SeanGroff.  The error happened twice before I pulled in your latest changes.  I am doing more work in the project now so I will report back if I see it again.  Just thought we should track on it in case it keeps coming up.

**Comment by SeanGroff** [comment]
> Currently running "3.15.5" @SeanGroff. The error happened twice before I pulled in your latest changes. I am doing more work in the project now so I will report back if I see it again. Just thought we should track on it in case it keeps coming up.

For sure.

I only knew of this issue because I spent hours troubleshooting only to find out next-auth released a bug that day causing this issue. They fixed it the following morning. If it happens again though, let me know.

**Comment by Chris-Boyle** [comment]
Just happened again.  I have been running the project for a while today.  Not sure if that impacts the memory usage and how it is not being cleaned up properly.
```
nextjs  |   64 |   const handleSubmit = (values, actions) => {
nextjs  |   65 |     saveDataCapture(phoneNumber, values);
nextjs  | wait  - compiling...
nextjs  | 
nextjs  | <--- Last few GCs --->
nextjs  | 
nextjs  | [18:0x55b88fcacda0] 15336515 ms: Mark-sweep 991.9 (999.1) -> 991.7 (999.6) MB, 399.0 / 0.1 ms  (average mu = 0.382, current mu = 0.137) allocation failure scavenge might not succeed
nextjs  | [18:0x55b88fcacda0] 15336922 ms: Mark-sweep 992.7 (1001.6) -> 992.3 (1002.4) MB, 388.0 / 0.1 ms  (average mu = 0.233, current mu = 0.045) allocation failure scavenge might not succeed
nextjs  | 
nextjs  | 
nextjs  | <--- JS stacktrace --->
nextjs  | 
nextjs  | FATAL ERROR: MarkCompactCollector: young object promotion failed Allocation failed - JavaScript heap out of memory
nextjs exited with code 0
```

**Comment by SeanGroff** [comment]
Instructed Chris Boyle to update the version of the SQForm Library to receive the bugfix to remove the Circular Dependencies.
Closing this issue. Will re-open if the issue persists after the update.

**Comment by Chris-Boyle** [comment]
I am seeing this issue a lot in the multi-instance-admin-views project.  I just started working on it.  @20BBrown14 did you ever see this error working on this project?
```
nextjs  | wait  - compiling...
nextjs  | 
nextjs  | <--- Last few GCs --->
nextjs  | 
nextjs  | [19:0x56156c1feea0]   368905 ms: Scavenge 910.5 (953.3) -> 908.6 (953.1) MB, 4.9 / 0.0 ms  (average mu = 0.982, current mu = 0.985) allocation failure 
nextjs  | [19:0x56156c1feea0]   368977 ms: Scavenge 921.3 (959.1) -> 912.2 (954.5) MB, 6.5 / 0.2 ms  (average mu = 0.982, current mu = 0.985) allocation failure 
nextjs  | [19:0x56156c1feea0]   369165 ms: Scavenge 916.8 (955.2) -> 915.2 (955.0) MB, 6.9 / 0.0 ms  (average mu = 0.982, current mu = 0.985) allocation failure 
nextjs  | 
nextjs  | 
nextjs  | <--- JS stacktrace --->
nextjs  | 
nextjs  | FATAL ERROR: MarkCompactCollector: young object promotion failed Allocation failed - JavaScript heap out of memory
nextjs exited with code 0

~/Projects/multi-instance-admin-views  AZT-1928-Add-Header-Components ✗
```

**Comment by 20BBrown14** [comment]
Hm 🤔 I did not have that issue. What commands are you using to run and what branch?

**Comment by Chris-Boyle** [comment]
It is pretty random.  Usually when re-compiling.  App throws an error.  I try a code change and when it re-compiles it sometimes crashes with the JS error.
