### ISSUE TITLE
Add SnackbarProvider to template 

### ISSUE THREAD

**Issue by Chris-Boyle** [SelectQuoteLabs/ancillary-external-app#8]
When trying to use the useSnackbarDispatch I found out that we didn't have the provider set up yet.

import { useSnackbarDispatch } from 'scplus-shared-components';

![image](https://user-images.githubusercontent.com/20329437/116278767-7065b980-a74c-11eb-970a-32f4a29fdd53.png)
![image](https://user-images.githubusercontent.com/20329437/116278790-765b9a80-a74c-11eb-94c4-e9a08efdfa5f.png)

**Comment by SeanGroff** [comment]
The PR referenced the PR number instead of the number for this issue. PR #12 closed this issue.
